// This file is auto-generated by ic-sql-migrate
// Do not edit manually

pub mod seed_001_test;
pub mod seed_002_more_data;

use ic_sql_migrate::Seed;

pub static SEEDS: &[Seed] = &[
    Seed::new("seed_001_test", seed_001_test::seed),
    Seed::new("seed_002_more_data", seed_002_more_data::seed),
];
