[package]
name = "sqlite"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.17"
ic-cdk = "0.18.7"
ic-rusqlite = "0.3.1"
migrations = { path = "../../packages/migrations" }

[build-dependencies]
migrations = { path = "../../packages/migrations" }
